---
title: "RB Page"
editor: visual
---

# Running Back Page

## RB rush attempt Leaders

```{r}
#| warning: false
#| results: hide
#| echo: false

library(quarto)
library(tidyverse)
library(nflverse)


rush_stats <- load_nextgen_stats(seasons = 2022, stat_type = 'rushing') #this has player GIS to make images with player images

t10_rushers <- rush_stats %>% 
  arrange(desc(rush_yards)) %>% 
  head(10)
```

```{r}
#| label: Rush Attempts
#| fig-cap: Top 10 RB Rush Yards.
#| warning: false
#| echo: false

ggplot(t10_rushers, aes(x = reorder(player_gsis_id, -rush_yards), y= rush_yards))+
  geom_col(aes(color = team_abbr, fill = team_abbr))+
  scale_color_nfl(type = "secondary")+
  scale_fill_nfl(alpha = 0.4)+
  labs(title = "2022 Rushing Leaders",
       y= "Number of Rush Yards")+
  theme_minimal()+
  theme(plot.title = ggplot2::element_text(face = "bold"),
        plot.title.position = "plot",
    axis.title.x = element_blank(),
    axis.text.x = element_nfl_headshot(size = 2)
  )
```

## Average Rushes Over Expected

```{r}
#| warning: false
#| echo: false

library(ggtext)
library(ggrepel)

id <- load_ff_playerids() %>% select(c(4,21)) %>% 
  rename(player_display_name = name)

next_gen <- load_nextgen_stats(season =2022, stat_type = c("rushing")) %>% 
  filter(week == 0)

ggplot(next_gen, aes(x = avg_rush_yards , y= rush_yards_over_expected_per_att))+geom_point(aes(),size = 3)+ 
  geom_smooth(method = "lm", se =F)+
  geom_hline(yintercept = 0)+
  scale_color_nfl(type = "secondary")+
  scale_fill_nfl(alpha = 0.4)+
  geom_text_repel(aes(label = player_display_name),verbose = TRUE,
                  seed = 123,
                  max.time = 1,
                  max.iter = Inf,
                  size = 3.25,
                  point.padding = 0.2, 
                  nudge_x = .05,
                  nudge_y = .05,
                  segment.linetype = 1)+
  xlab("Average Rush Yard Per Attempt")+
  ylab("Rush Yards Over Expected Per Attempt")+
  labs(title = "2022 RB Rushing Yards by Expected Yards")+
  theme_bw()

  
```
